<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GeneratedVideosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('videos')->delete();

        \DB::table('videos')->insert(array (
            0 =>
            array (
                'id' => 1,
                'user_id' => 1,
                'title' => 'Tenet',
                'slug' => 'tenet-2020',
                'description' => 'Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
                'views' => 31,
                'runtime' => '150 min',
                'year' => '2020',
                'imdb_id' => 'tt6723592',
                'tmdb_id' => '577922',
                'imdb_rating' => '7.5',
                'genres' => '["Action"," Sci-Fi"," Thriller"]',
                'country' => '["UK"," USA"]',
                'type' => 'movie',
                'directors' => '["Christopher Nolan"]',
                'actors' => '["Juhan Ulfsak"," Jefferson Hall"," Ivo Uukkivi"," Andrew Howard"]',
                'box_office' => '$57,929,000',
                'poster' => '/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'PG-13',
                'status' => 1,
                'created_at' => '2021-03-02 08:27:09',
                'updated_at' => '2022-01-25 18:54:12',
            ),
            1 =>
            array (
                'id' => 2,
                'user_id' => 1,
                'title' => 'Soul',
                'slug' => 'soul-2020',
                'description' => 'After landing the gig of a lifetime, a New York jazz pianist suddenly finds himself trapped in a strange land between Earth and the afterlife.',
                'views' => 14,
                'runtime' => '100 min',
                'year' => '2020',
                'imdb_id' => 'tt2948372',
                'tmdb_id' => '508442',
                'imdb_rating' => '8.1',
                'genres' => '["Animation"," Adventure"," Comedy"," Family"," Fantasy"," Music"]',
                'country' => '["USA"]',
                'type' => 'movie',
            'directors' => '["Pete Docter"," Kemp Powers(co-director)"]',
                'actors' => '["Jamie Foxx"," Tina Fey"," Graham Norton"," Rachel House"]',
                'box_office' => 'N/A',
                'poster' => '/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'PG',
                'status' => 1,
                'created_at' => '2021-03-02 08:31:04',
                'updated_at' => '2022-02-13 02:07:21',
            ),
            2 =>
            array (
                'id' => 3,
                'user_id' => 1,
                'title' => 'Joker',
                'slug' => 'joker-2019',
                'description' => 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.',
                'views' => 8,
                'runtime' => '122 min',
                'year' => '2019',
                'imdb_id' => 'tt7286456',
                'tmdb_id' => '475557',
                'imdb_rating' => '8.4',
                'genres' => '["Crime"," Drama"," Thriller"]',
                'country' => '["USA"," Canada"]',
                'type' => 'movie',
                'directors' => '["Todd Phillips"]',
                'actors' => '["Joaquin Phoenix"," Robert De Niro"," Zazie Beetz"," Frances Conroy"]',
                'box_office' => '$335,451,311',
                'poster' => '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'R',
                'status' => 1,
                'created_at' => '2021-03-02 08:32:00',
                'updated_at' => '2022-02-13 02:06:36',
            ),
            3 =>
            array (
                'id' => 4,
                'user_id' => 1,
                'title' => 'Parasite',
                'slug' => 'parasite-2019',
                'description' => 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
                'views' => 11,
                'runtime' => '132 min',
                'year' => '2019',
                'imdb_id' => 'tt6751668',
                'tmdb_id' => '496243',
                'imdb_rating' => '8.6',
                'genres' => '["Comedy"," Drama"," Thriller"]',
                'country' => '["South Korea"]',
                'type' => 'movie',
                'directors' => '["Bong Joon Ho"]',
                'actors' => '["Kang-ho Song"," Lee Sun-kyun"," Yeo-jeong Cho"," Choi Woo-sik"]',
                'box_office' => '$53,369,749',
                'poster' => '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'R',
                'status' => 1,
                'created_at' => '2021-03-02 08:43:17',
                'updated_at' => '2022-02-13 02:07:26',
            ),
            4 =>
            array (
                'id' => 6,
                'user_id' => 1,
                'title' => 'The Shawshank Redemption',
                'slug' => 'the-shawshank-redemption-1994',
                'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
                'views' => 2,
                'runtime' => '142 min',
                'year' => '1994',
                'imdb_id' => 'tt0111161',
                'tmdb_id' => '278',
                'imdb_rating' => '9.3',
                'genres' => '["Drama"]',
                'country' => '["USA"]',
                'type' => 'movie',
                'directors' => '["Frank Darabont"]',
                'actors' => '["Tim Robbins"," Morgan Freeman"," Bob Gunton"," William Sadler"]',
                'box_office' => '$28,699,976',
                'poster' => '/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'R',
                'status' => 1,
                'created_at' => '2021-03-02 08:47:17',
                'updated_at' => '2022-02-13 02:06:04',
            ),
            5 =>
            array (
                'id' => 7,
                'user_id' => 1,
                'title' => 'Inception',
                'slug' => 'inception-2010',
                'description' => 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
                'views' => 1,
                'runtime' => '148 min',
                'year' => '2010',
                'imdb_id' => 'tt1375666',
                'tmdb_id' => '27205',
                'imdb_rating' => '8.8',
                'genres' => '["Action"," Adventure"," Sci-Fi"," Thriller"]',
                'country' => '["USA"," UK"]',
                'type' => 'movie',
                'directors' => '["Christopher Nolan"]',
                'actors' => '["Leonardo DiCaprio"," Joseph Gordon-Levitt"," Elliot Page"," Tom Hardy"]',
                'box_office' => '$292,576,195',
                'poster' => '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'PG-13',
                'status' => 1,
                'created_at' => '2021-03-02 08:48:15',
                'updated_at' => '2021-03-02 12:37:36',
            ),
            6 =>
            array (
                'id' => 8,
                'user_id' => 1,
                'title' => 'Interstellar',
                'slug' => 'interstellar-2014',
                'description' => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
                'views' => 50,
                'runtime' => '169 min',
                'year' => '2014',
                'imdb_id' => 'tt0816692',
                'tmdb_id' => '157336',
                'imdb_rating' => '8.6',
                'genres' => '["Adventure"," Drama"," Sci-Fi"]',
                'country' => '["USA"," UK"," Canada"]',
                'type' => 'movie',
                'directors' => '["Christopher Nolan"]',
                'actors' => '["Ellen Burstyn"," Matthew McConaughey"," Mackenzie Foy"," John Lithgow"]',
                'box_office' => '$188,020,017',
                'poster' => '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'PG-13',
                'status' => 1,
                'created_at' => '2021-03-02 08:49:37',
                'updated_at' => '2022-02-13 02:04:40',
            ),
            7 =>
            array (
                'id' => 9,
                'user_id' => 1,
                'title' => 'The Dark Knight',
                'slug' => 'the-dark-knight-2008',
                'description' => 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
                'views' => 3,
                'runtime' => '152 min',
                'year' => '2008',
                'imdb_id' => 'tt0468569',
                'tmdb_id' => '155',
                'imdb_rating' => '9.0',
                'genres' => '["Action"," Crime"," Drama"," Thriller"]',
                'country' => '["USA"," UK"]',
                'type' => 'movie',
                'directors' => '["Christopher Nolan"]',
                'actors' => '["Christian Bale"," Heath Ledger"," Aaron Eckhart"," Michael Caine"]',
                'box_office' => '$534,858,444',
                'poster' => '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'PG-13',
                'status' => 1,
                'created_at' => '2021-03-02 08:49:52',
                'updated_at' => '2022-01-12 05:27:54',
            ),
            8 =>
            array (
                'id' => 10,
                'user_id' => 1,
                'title' => 'Forrest Gump',
                'slug' => 'forrest-gump-1994',
                'description' => 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
                'views' => 9,
                'runtime' => '142 min',
                'year' => '1994',
                'imdb_id' => 'tt0109830',
                'tmdb_id' => '13',
                'imdb_rating' => '8.8',
                'genres' => '["Drama"," Romance"]',
                'country' => '["USA"]',
                'type' => 'movie',
                'directors' => '["Robert Zemeckis"]',
                'actors' => '["Tom Hanks"," Rebecca Williams"," Sally Field"," Michael Conner Humphreys"]',
                'box_office' => '$330,455,270',
                'poster' => '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'PG-13',
                'status' => 1,
                'created_at' => '2021-03-02 08:50:01',
                'updated_at' => '2022-01-17 23:49:54',
            ),
            9 =>
            array (
                'id' => 11,
                'user_id' => 1,
                'title' => 'Fight Club',
                'slug' => 'fight-club-1999',
                'description' => 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
                'views' => 0,
                'runtime' => '139 min',
                'year' => '1999',
                'imdb_id' => 'tt0137523',
                'tmdb_id' => '550',
                'imdb_rating' => '8.8',
                'genres' => '["Drama"]',
                'country' => '["Germany"," USA"]',
                'type' => 'movie',
                'directors' => '["David Fincher"]',
                'actors' => '["Edward Norton"," Brad Pitt"," Meat Loaf"," Zach Grenier"]',
                'box_office' => '$37,030,102',
                'poster' => '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'R',
                'status' => 1,
                'created_at' => '2021-03-02 08:50:31',
                'updated_at' => '2021-03-02 08:50:31',
            ),
            10 =>
            array (
                'id' => 12,
                'user_id' => 1,
                'title' => 'Shutter Island',
                'slug' => 'shutter-island-2010',
                'description' => 'In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.',
                'views' => 1,
                'runtime' => '138 min',
                'year' => '2010',
                'imdb_id' => 'tt1130884',
                'tmdb_id' => '11324',
                'imdb_rating' => '8.2',
                'genres' => '["Mystery"," Thriller"]',
                'country' => '["USA"]',
                'type' => 'movie',
                'directors' => '["Martin Scorsese"]',
                'actors' => '["Leonardo DiCaprio"," Mark Ruffalo"," Ben Kingsley"," Max von Sydow"]',
                'box_office' => '$128,012,934',
                'poster' => '/4GDy0PHYX3VRXUtwK5ysFbg3kEx.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'R',
                'status' => 1,
                'created_at' => '2021-03-02 08:50:58',
                'updated_at' => '2021-03-04 03:46:43',
            ),
            11 =>
            array (
                'id' => 13,
                'user_id' => 1,
                'title' => 'Saving Private Ryan',
                'slug' => 'saving-private-ryan-1998',
                'description' => 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
                'views' => 5,
                'runtime' => '169 min',
                'year' => '1998',
                'imdb_id' => 'tt0120815',
                'tmdb_id' => '857',
                'imdb_rating' => '8.6',
                'genres' => '["Drama"," War"]',
                'country' => '["USA"]',
                'type' => 'movie',
                'directors' => '["Steven Spielberg"]',
                'actors' => '["Tom Hanks"," Tom Sizemore"," Edward Burns"," Barry Pepper"]',
                'box_office' => '$217,049,603',
                'poster' => '/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'R',
                'status' => 1,
                'created_at' => '2021-03-02 08:51:11',
                'updated_at' => '2021-03-24 12:25:47',
            ),
            12 =>
            array (
                'id' => 14,
                'user_id' => 1,
                'title' => 'Jack Reacher',
                'slug' => 'jack-reacher-2012',
                'description' => 'A homicide investigator digs deeper into a case involving a trained military sniper who shot five random victims.',
                'views' => 11,
                'runtime' => '130 min',
                'year' => '2012',
                'imdb_id' => 'tt0790724',
                'tmdb_id' => '75780',
                'imdb_rating' => '7.0',
                'genres' => '["Action"," Thriller"]',
                'country' => '["USA"]',
                'type' => 'movie',
                'directors' => '["Christopher McQuarrie"]',
                'actors' => '["Tom Cruise"," Rosamund Pike"," Richard Jenkins"," David Oyelowo"]',
                'box_office' => '$80,070,736',
                'poster' => '/uQBbjrLVsUibWxNDGA4Czzo8lwz.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'PG-13',
                'status' => 1,
                'created_at' => '2021-03-02 08:51:26',
                'updated_at' => '2021-12-06 12:17:22',
            ),
            13 =>
            array (
                'id' => 15,
                'user_id' => 1,
                'title' => 'Mission: Impossible',
                'slug' => 'mission-impossible-1996',
                'description' => 'An American agent, under false suspicion of disloyalty, must discover and expose the real spy without the help of his organization.',
                'views' => 142,
                'runtime' => '110 min',
                'year' => '1996',
                'imdb_id' => 'tt0117060',
                'tmdb_id' => '954',
                'imdb_rating' => '7.1',
                'genres' => '["Action"," Adventure"," Thriller"]',
                'country' => '["USA"]',
                'type' => 'movie',
                'directors' => '["Brian De Palma"]',
                'actors' => '["Tom Cruise"," Jon Voight"," Emmanuelle B\\u00e9art"," Henry Czerny"]',
                'box_office' => '$180,981,856',
                'poster' => '/l5uxY5m5OInWpcExIpKG6AR3rgL.jpg',
                'video' => 'https://res.cloudinary.com/newagedevs/video/upload/v1624855524/nxplay/videos/Bathroom_Fight_Scene_-_Tom_Cruise_Henry_Cavill_-_Mission-_Impossible-_Fallout_-_Netflix_India_mixlsr.mp4',
                'photos' => '[]',
                'age_rating' => 'PG-13',
                'status' => 1,
                'created_at' => '2021-03-02 08:51:35',
                'updated_at' => '2022-02-24 00:50:43',
            ),
            14 =>
            array (
                'id' => 16,
                'user_id' => 1,
                'title' => 'The Man from Nowhere',
                'slug' => 'the-man-from-nowhere-2010',
                'description' => 'A quiet pawnshop keeper with a violent past takes on a drug-and-organ trafficking ring in hope of saving the child who is his only friend.',
                'views' => 15,
                'runtime' => '119 min',
                'year' => '2010',
                'imdb_id' => 'tt1527788',
                'tmdb_id' => '51608',
                'imdb_rating' => '7.8',
                'genres' => '["Action"," Crime"," Drama"," Thriller"]',
                'country' => '["South Korea"]',
                'type' => 'movie',
                'directors' => '["Jeong-beom Lee"]',
                'actors' => '["Won Bin"," Sae-ron Kim"," Tae-hoon Kim"," Hee-won Kim"]',
                'box_office' => '$528,175',
                'poster' => '/ld19CFIo27t41JXSGZdaPMUGTxh.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'R',
                'status' => 1,
                'created_at' => '2021-03-03 07:31:58',
                'updated_at' => '2022-02-13 02:07:39',
            ),
            15 =>
            array (
                'id' => 17,
                'user_id' => 1,
                'title' => 'The Yellow Sea',
                'slug' => 'the-yellow-sea-2010',
                'description' => 'When the attempt to kill a professor goes wrong, a series of violent events are triggered which force a taxi driver to run for his life.',
                'views' => 104,
                'runtime' => '136 min',
                'year' => '2010',
                'imdb_id' => 'tt1230385',
                'tmdb_id' => '57361',
                'imdb_rating' => '7.3',
                'genres' => '["Action"," Crime"," Drama"," Thriller"]',
                'country' => '["South Korea"," USA"," Hong Kong"]',
                'type' => 'movie',
                'directors' => '["Hong-jin Na"]',
                'actors' => '["Jung-woo Ha"," Kim Yoon-seok"," Jo Sung-ha"," Cheol-min Lee"]',
                'box_office' => 'N/A',
                'poster' => '/16Pkg2ChCdACbBKVIAPAZtLL6eb.jpg',
                'video' => 'video.mp4',
                'photos' => '[]',
                'age_rating' => 'R',
                'status' => 1,
                'created_at' => '2021-03-03 07:57:54',
                'updated_at' => '2022-03-28 11:34:15',
            ),
        ));


    }
}
